# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Koko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fold', models.CharField(default='2 FOLD AUTOMATIC', max_length=1000)),
                ('pattern', models.CharField(max_length=1000)),
                ('color', models.CharField(default='GRAY', max_length=1000)),
                ('description', models.CharField(default='Two Fold Automatic Umbrella with Superior Nylon Fabric, Best Quality Frame and Matching Handle.', max_length=1000)),
                ('pic1', models.ImageField(blank=True, default='', max_length=1000, upload_to='')),
                ('pic2', models.ImageField(blank=True, default='', max_length=1000, upload_to='')),
                ('pic3', models.ImageField(blank=True, default='', max_length=1000, upload_to='')),
                ('pic4', models.ImageField(blank=True, default='', max_length=1000, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Umbrella',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fold', models.CharField(default='3 FOLD AUTOMATIC', max_length=1000)),
                ('pattern', models.CharField(max_length=1000)),
                ('color', models.CharField(default='GRAY', max_length=1000)),
                ('description', models.CharField(default='Three Fold Automatic Umbrella with Superior Nylon Fabric, Best Quality Frame and Matching Handle.', max_length=1000)),
                ('pic1', models.ImageField(blank=True, default='', max_length=1000, upload_to='')),
                ('pic2', models.ImageField(blank=True, default='', max_length=1000, upload_to='')),
                ('pic3', models.ImageField(blank=True, default='', max_length=1000, upload_to='')),
                ('pic4', models.ImageField(blank=True, default='', max_length=1000, upload_to='')),
            ],
        ),
    ]
